#!/bin/bash
# Script to start webrtc2sip on background (whitout a terminal mutiplexer)
## Copyright 2014, Jorge Fonseca - http://jorge.fonseca.ec

## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at

##    http://www.apache.org/licenses/LICENSE-2.0

## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
# Check for requirements
if [ $# -eq 1 ]; then
	# path of the webrtc binary
	WEBRTC=/usr/local/sbin/webrtc2sip
	CONFIG=$1
	# command to execute
	COMAND=$($WEBRTC --config=$CONFIG < /dev/random > /dev/null 2>&1 &)
	exit 0
else

	echo "Usage: $0 [CONFIGURATION_FILE]"
	exit 2
fi